### ISSUE TITLE
Memory Usage During Trace Expansion

### ISSUE THREAD

**Issue by DavePearce** [Consensys/go-corset#307]
There appears to be an issue where trace expansion can lead to very high memory usage on very large traces.  This is likely to be partly caused by concurrency generating high memory pressure.  Therefore, batching go-routines could reduce this pressure.

**Comment by achintya-7** [comment]
Hey @DavePearce  
I would like to work on this issue. 
Adding a worker-queue [here](https://github.com/Consensys/go-corset/blob/f82251161d4fac38b5d2ccf1a068e3410f63c97f/pkg/schema/builder.go#L322) for limiting number of go-routines should help with memory.

**Comment by DavePearce** [comment]
Well, at this stage, its not a particularly big problem for us.  I have used batch processing for the various parts which have helped.

**Comment by achintya-7** [comment]
> Well, at this stage, its not a particularly big problem for us.  I have used batch processing for the various parts which have helped.

Ah cool.
Well I did implement a generic worker queue and incorporated it with this function. If you want, I can raise a PR.
